# Generated by Django 3.2.18 on 2023-03-13 08:00

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=255)),
                ('PL_DATE', models.DateTimeField(auto_now_add=True)),
                ('SPR_USER_FIN_ID', models.IntegerField(default=django.contrib.auth.models.User)),
                ('UPL_DOCS_IMAGE_ID', models.IntegerField(max_length=255)),
                ('REG_DATE', models.DateTimeField(auto_now_add=True)),
                ('PL_NUMBER', models.IntegerField(max_length=255)),
                ('SROK_DEISTV', models.DateTimeField(auto_now_add=True)),
                ('SPR_ORG_ID', models.IntegerField(max_length=255)),
                ('SPR_AUTO_ID', models.IntegerField(max_length=255)),
                ('SPR_DRIVER_ID', models.IntegerField(max_length=255)),
                ('SPR_MARK_TOPL_ID', models.IntegerField(max_length=255)),
                ('SPR_REZHIM_ID', models.IntegerField(max_length=255)),
                ('VYIEZD_SPEEDOMETER', models.IntegerField(max_length=255)),
                ('VYIEZD_TIME', models.DateTimeField(auto_now_add=True)),
                ('VOZVR_SPEEDOMETER', models.IntegerField(max_length=255)),
                ('VOZVR_TIME', models.DateTimeField(auto_now_add=True)),
                ('DG_VYIDANO', models.IntegerField(max_length=255)),
                ('DG_OST_VYIEZD', models.IntegerField(max_length=255)),
                ('DG_OST_VOZVR', models.IntegerField(max_length=255)),
                ('VR_SPECOB', models.CharField(max_length=255)),
                ('VR_DVIG', models.CharField(max_length=255)),
                ('ZAKAZCHIK', models.CharField(max_length=255)),
                ('TIME_PRIB', models.CharField(max_length=255)),
                ('TIME_UB', models.CharField(max_length=255)),
                ('TYPE_WORK', models.CharField(max_length=255)),
                ('DATE_DOP', models.DateTimeField(auto_now_add=True)),
                ('DATE_CONTROL', models.DateTimeField(auto_now_add=True)),
                ('FIO_MEH', models.CharField(max_length=25)),
                ('FIO_MEH_PRIN', models.CharField(max_length=25)),
                ('KOLONNA', models.CharField(max_length=25)),
                ('BRIGADA', models.CharField(max_length=25)),
                ('FIO_DISP', models.CharField(max_length=25)),
                ('SPR_SER_ID', models.IntegerField(max_length=255)),
            ],
        ),
    ]
