# Generated by Django 3.2.18 on 2023-03-13 08:01

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_table',
            name='SPR_USER_FIN_ID',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=255),
        ),
    ]
