# Generated by Django 3.2.18 on 2023-03-13 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('putlist', '0003_alter_url_table_spr_user_fin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url_table',
            name='SPR_USER_FIN_ID',
        ),
        migrations.AddField(
            model_name='url_table',
            name='SPR_USER_FIN_ID',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
