# Generated by Django 3.2.18 on 2023-03-13 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('putlist', '0004_auto_20230313_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url_table',
            name='SPR_USER_FIN_ID',
        ),
        migrations.AddField(
            model_name='url_table',
            name='SPR_USER_FIN_ID',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
