# Generated by Django 3.2.18 on 2023-03-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0005_auto_20230313_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url_table',
            options={'verbose_name': 'Путевой лист', 'verbose_name_plural': 'Путевой лист'},
        ),
        migrations.AlterField(
            model_name='url_table',
            name='NAME',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
