# Generated by Django 3.2.18 on 2023-03-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0006_auto_20230313_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_table',
            name='PL_DATE',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата документа'),
        ),
    ]
