# Generated by Django 3.2.18 on 2023-03-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0007_alter_url_table_pl_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_table',
            name='PL_DATE',
            field=models.DateTimeField(verbose_name='Дата документа'),
        ),
    ]
