# Generated by Django 3.2.18 on 2023-03-13 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0010_auto_20230313_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_table',
            name='SPR_AUTO_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='putlist.spr_auto', verbose_name='Код автомобиля'),
        ),
        migrations.AlterField(
            model_name='url_table',
            name='SPR_DRIVER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='putlist.spr_driver', verbose_name='Код водителя'),
        ),
        migrations.AlterField(
            model_name='url_table',
            name='SPR_MARK_TOPL_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='putlist.spr_mark_topl', verbose_name='Код марки топлива'),
        ),
        migrations.AlterField(
            model_name='url_table',
            name='SPR_ORG_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='putlist.spr_org', verbose_name='Код организации'),
        ),
        migrations.AlterField(
            model_name='url_table',
            name='SPR_REZHIM_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='putlist.spr_rezhim', verbose_name='Код режима работы'),
        ),
    ]
