# Generated by Django 3.2.18 on 2023-03-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0013_alter_spr_ser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spr_auto',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
