# Generated by Django 3.2.18 on 2023-03-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0016_auto_20230313_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url_table',
            name='SPR_AUTO_ID',
        ),
        migrations.RemoveField(
            model_name='url_table',
            name='SPR_DRIVER_ID',
        ),
        migrations.RemoveField(
            model_name='url_table',
            name='SPR_MARK_TOPL_ID',
        ),
        migrations.RemoveField(
            model_name='url_table',
            name='SPR_ORG_ID',
        ),
        migrations.RemoveField(
            model_name='url_table',
            name='SPR_REZHIM_ID',
        ),
    ]
