# Generated by Django 3.2.18 on 2023-03-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0017_auto_20230313_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spr_auto',
            name='GOS_NUM',
            field=models.CharField(max_length=255, verbose_name='Гос.номер'),
        ),
        migrations.AlterField(
            model_name='spr_ser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
