# Generated by Django 3.2.18 on 2023-03-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0018_auto_20230313_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_table',
            name='DG_OST_VOZVR',
            field=models.IntegerField(max_length=255, verbose_name='Движение горючего остаток горючего при возвращении'),
        ),
        migrations.AlterField(
            model_name='url_table',
            name='DG_OST_VYIEZD',
            field=models.IntegerField(max_length=255, verbose_name='Движение горючего остаток горючего при выезде'),
        ),
        migrations.AlterField(
            model_name='url_table',
            name='DG_VYIDANO',
            field=models.IntegerField(max_length=255, verbose_name='Движение горючего выдано'),
        ),
        migrations.AlterField(
            model_name='url_table',
            name='VOZVR_SPEEDOMETER',
            field=models.IntegerField(max_length=255, verbose_name='Показания спидометра по возваращению'),
        ),
        migrations.AlterField(
            model_name='url_table',
            name='VYIEZD_SPEEDOMETER',
            field=models.IntegerField(max_length=255, verbose_name='Показания спидометра при выезде'),
        ),
    ]
