# Generated by Django 3.2.18 on 2023-03-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0021_auto_20230313_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spr_org',
            name='NAME',
            field=models.CharField(max_length=255, verbose_name='Наименования Организации'),
        ),
        migrations.AlterField(
            model_name='spr_org',
            name='SHTAMP',
            field=models.CharField(max_length=255, verbose_name='Штамп организации (левый верхний угол)'),
        ),
    ]
