# Generated by Django 3.2.18 on 2023-03-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0024_auto_20230313_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spr_mark_topl',
            options={'verbose_name': 'Марка топлива', 'verbose_name_plural': 'Марка топлива'},
        ),
    ]
