# Generated by Django 3.2.18 on 2023-03-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0025_alter_spr_mark_topl_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spr_driver',
            name='FIO',
            field=models.CharField(db_index=True, max_length=100, verbose_name='ФИО Водителя полностью'),
        ),
    ]
