# Generated by Django 3.2.18 on 2023-03-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0029_auto_20230327_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url_table',
            name='TIME_PRIB',
        ),
        migrations.RemoveField(
            model_name='url_table',
            name='TIME_UB',
        ),
        migrations.RemoveField(
            model_name='url_table',
            name='TYPE_WORK',
        ),
        migrations.RemoveField(
            model_name='url_table',
            name='ZAKAZCHIK',
        ),
    ]
