# Generated by Django 3.2.18 on 2023-03-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0030_auto_20230327_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaz',
            name='Z_NUM',
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='UPL_TABLE_ID',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер записи Путевого листа'),
        ),
    ]
