# Generated by Django 3.2.18 on 2023-03-28 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0031_auto_20230327_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_table',
            name='ZADAN',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='putlist.zakaz'),
        ),
    ]
