# Generated by Django 3.2.18 on 2023-03-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0032_url_table_zadan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url_table',
            name='ZADAN',
        ),
        migrations.AddField(
            model_name='url_table',
            name='ZADAN',
            field=models.ManyToManyField(default=0, to='putlist.ZAKAZ'),
        ),
    ]
