# Generated by Django 3.2.18 on 2023-03-28 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0033_auto_20230328_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url_table',
            name='ZADAN',
        ),
        migrations.AddField(
            model_name='url_table',
            name='ZADAN',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='putlist.zakaz'),
        ),
    ]
