# Generated by Django 3.2.18 on 2023-03-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0034_auto_20230328_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url_table',
            name='ZADAN',
        ),
    ]
