# Generated by Django 3.2.18 on 2023-03-28 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0035_remove_url_table_zadan'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_table',
            name='ZADAN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='putlist.zakaz'),
        ),
    ]
