# Generated by Django 3.2.18 on 2023-03-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0043_auto_20230328_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_table',
            name='ZADAN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='putlist.zakaz'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='UPL_TABLE_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='putlist.url_table'),
        ),
    ]
