# Generated by Django 3.2.18 on 2023-03-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0044_auto_20230328_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url_table',
            name='ZADAN',
        ),
    ]
