# Generated by Django 3.2.18 on 2023-03-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0049_alter_zakaz_upl_table_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zakaz',
            options={'verbose_name': 'Заказчики', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.RemoveField(
            model_name='url_table',
            name='ZADAN',
        ),
    ]
