# Generated by Django 3.2.18 on 2023-03-28 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0050_auto_20230328_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='UPL_TABLE_ID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='putlist.url_table'),
        ),
    ]
