# Generated by Django 3.2.18 on 2023-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0054_alter_zakaz_upl_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_table',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
