# Generated by Django 3.2.18 on 2023-03-28 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0056_alter_zakaz_upl_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_table',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='UPL_TABLE_ID',
            field=models.ForeignKey(blank=True, default='e65ac90f6fdf486d9e618f3b4818d3b8', on_delete=django.db.models.deletion.CASCADE, to='putlist.url_table'),
        ),
    ]
