# Generated by Django 3.2.18 on 2023-03-29 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0063_alter_zakaz_upl_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='UPL_TABLE_ID',
            field=models.ForeignKey(blank=True, default='4108e77c5d68451fa6a2004e777bba92', on_delete=django.db.models.deletion.CASCADE, to='putlist.url_table'),
        ),
    ]
