# Generated by Django 3.2.18 on 2023-04-04 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0067_alter_zakaz_upl_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_table',
            name='SPR_AUTO_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='putlist.spr_auto', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='url_table',
            name='SPR_DRIVER_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='putlist.spr_driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='url_table',
            name='SPR_MARK_TOPL_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='putlist.spr_mark_topl', verbose_name='Марка топлива'),
        ),
        migrations.AlterField(
            model_name='url_table',
            name='SPR_ORG_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='putlist.spr_org', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='url_table',
            name='SPR_REZHIM_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='putlist.spr_rezhim', verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='url_table',
            name='UPL_DOCS_IMAGE_ID',
            field=models.ImageField(max_length=255, null=True, upload_to='putlist/', verbose_name='Образ подписанного путевого листа'),
        ),
    ]
