# Generated by Django 3.2.18 on 2023-04-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0068_auto_20230404_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_table',
            name='BRIGADA',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Бригада'),
        ),
        migrations.AlterField(
            model_name='url_table',
            name='KOLONNA',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Колонна'),
        ),
    ]
