# Generated by Django 3.2.18 on 2023-04-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0069_auto_20230404_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_table',
            name='VR_SPECOB',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Время работы спецоборудования'),
        ),
        migrations.AlterField(
            model_name='url_table',
            name='VYIEZD_TIME',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время выезда фактическое, д/м/г м/ч'),
        ),
    ]
