# Generated by Django 3.2.18 on 2023-04-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0072_alter_url_table_upl_docs_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_table',
            name='DG_OST_VOZVR',
            field=models.IntegerField(blank=True, null=True, verbose_name='Движение горючего остаток горючего при возвращении'),
        ),
    ]
