# Generated by Django 3.2.18 on 2023-04-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0073_alter_url_table_dg_ost_vozvr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='UPL_TABLE_ID',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='putlist.url_table'),
        ),
    ]
