# Generated by Django 3.2.18 on 2023-04-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0074_alter_zakaz_upl_table_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url_table',
            name='PL_NUMBER',
        ),
    ]
