# Generated by Django 3.2.18 on 2023-04-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0075_remove_url_table_pl_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_table',
            name='PROBEG',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пробег'),
        ),
    ]
