# Generated by Django 3.2.18 on 2023-04-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0076_url_table_probeg'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_table',
            name='RASHOD',
            field=models.IntegerField(blank=True, null=True, verbose_name='Расход'),
        ),
    ]
