# Generated by Django 3.2.18 on 2023-04-07 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0077_url_table_rashod'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_table',
            name='STATUS',
            field=models.CharField(choices=[('O', 'Открытый'), ('L', 'Закрытый')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
