# Generated by Django 3.2.18 on 2023-04-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0082_alter_url_table_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_table',
            name='nomer',
            field=models.IntegerField(default=0),
        ),
    ]
