# Generated by Django 3.2.18 on 2023-04-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0084_remove_url_table_nomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_table',
            name='nomer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
