# Generated by Django 3.2.18 on 2023-04-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0085_url_table_nomer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url_table',
            options={'managed': True, 'verbose_name': 'Путевой лист'},
        ),
    ]
