# Generated by Django 3.2.18 on 2023-04-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0088_alter_url_table_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url_table',
            name='nomer',
        ),
    ]
