# Generated by Django 3.2.18 on 2023-04-11 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0089_remove_url_table_nomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_table',
            name='SPR_SER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='putlist.spr_ser', verbose_name='Код серии документа'),
        ),
    ]
