# Generated by Django 3.2.18 on 2023-04-24 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0090_alter_url_table_spr_ser_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url_table',
            options={'managed': True, 'ordering': ['-date'], 'verbose_name': 'Путевой лист'},
        ),
        migrations.AddField(
            model_name='url_table',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
