# Generated by Django 3.2.18 on 2023-04-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0091_auto_20230424_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url_table',
            name='NAME',
        ),
    ]
