# Generated by Django 3.2.18 on 2023-05-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0094_auto_20230503_0319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url_table',
            options={'managed': True, 'ordering': ['-REG_DATE'], 'verbose_name': 'Путевой лист'},
        ),
        migrations.AlterField(
            model_name='url_table',
            name='PL_DATE',
            field=models.DateTimeField(verbose_name='Дата документа'),
        ),
        migrations.AlterField(
            model_name='url_table',
            name='REG_DATE',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
    ]
