# Generated by Django 3.2.18 on 2023-05-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0095_auto_20230503_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_table',
            name='DG_VYIDANO',
            field=models.IntegerField(blank=True, null=True, verbose_name='Движение горючего выдано'),
        ),
    ]
