# Generated by Django 3.2.18 on 2023-05-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putlist', '0097_alter_url_table_date_dop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='COMMENTS',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Особые отметки'),
        ),
    ]
